#!/bin/bash

CONFFILE="$HOME/.config/upm/upm.conf"


# usage $EXITCODE $MESSAGE
# Print usage and die() with the given message and exit code.
usage ()
{
    cat << EOF >&2
Usage:
    $(basename $0) [-o | -c] [-h <hostname>] [-b <command>] [<key> | pass <key> | user <key> | ls]

Remote access to upm, an ultra-minimalistic password manager.

Commands:
    pass <key>  (Default) Get password corresponding to the key.
                If just the key is given, this is the default.
    user <key>  Get the username corresponding to the key.
    ls          List all keys in vault. Outputs to stdout.

Options:
    -h <hostname>   Run upm with ssh in host <hostname>.
                    If this option is not given, the value of variable
                    'RUPM_HOST' from the environment or configuration
                    file is used.
    -b <command>    Use <command> as the upm binary in the remote host,
                    e.g. '~/bin/upm'.
                    If this option is not given, the value of variable
                    'REMOTE_UPM_BIN' from the environment or configuration
                    file is used.
    -c              Output to xclip (default).
    -o              Output to standard output.

Uses configuration from '$CONFFILE' if it exists.
EOF
    echo "" >&2
    die "$1" "$2"
}

# die $EXITCODE $MESSAGE
# Print a message and exit
die ()
{
    echo "$2" >&2
    exit $1
}

# Places the input from stdin to clipboard with xclip. Removes the input
# from clipboard after $CLEARTIME seconds and allows $PASTES pastes.
xclip_output ()
{
    local CLEARTIME PASTES PWSHA
    CLEARTIME=30
    PASTES=2

    PWSHA=$(cat | xclip -i -f -loops $PASTES | sha256sum)
    ( sleep $CLEARTIME ; \
        [ "$PWSHA" = "$(xclip -o | sha256sum)" ] && echo -n "" | xclip -i ) & \
        disown
}

[ $# -le 4 ] && [ $# -ge 1 ] || usage 1 "Error: Wrong number of arguments"

RCMD=pass
OUTPUT="xclip_output"
while [ $# -gt 0 ] ; do
    PAR=$1
    case $PAR in
        pass) # get password (default)
            RCMD=pass ;;
        user) # get username
            RCMD=user ;;
        ls) # get username
            RCMD=ls
            OUTPUT=cat ;;
        -h) # remote host
            RUPM_HOST="$PAR" ;;
        -b) # remote command
            REMOTE_UPM_BIN="$PAR" ;;
        -o) # output to stdout
            OUTPUT=cat ;;
        -c) # output to xclip (default)
            OUTPUT="xclip_output" ;;
        -*)
            usage 1 "Error: Unknown option ${PAR}." ;;
        *)
            KEY="$PAR" ;;
    esac
    shift
done

REMOTE_UPM_BIN=${REMOTE_UPM_BIN:-"upm"}
[ -r "$CONFFILE" ] && source "$CONFFILE"
[ -z "$RUPM_HOST" ] && usage 2 "Error: Remote host not given."
[ "$RCMD" != "ls" ] && [ -z "$KEY" ] \
    && usage 2 "Error: No key given."
[ "$RCMD" = "ls" ] && [ -n "$KEY" ] \
    && usage 2 "Error: Key argument given with '$(basename $0) ls'."
[ "$OUTPUT" = "xclip_output" ] && ! xclip -h &> /dev/null \
    && die 1 "$(basename $0) requires xclip for clipboard output."

[ -t 0 ] && stty -echo
# printf removes newline
printf "%s" "$(ssh ${RUPM_HOST} ${REMOTE_UPM_BIN} -o -p ${RCMD} ${KEY})" \
    | $OUTPUT
[ -t 0 ] && stty echo

if [ "$OUTPUT" = "xclip_output" ] ; then
    echo "Output sent to clipboard." >&2
else
    echo "" >&2
fi
